// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVSBSBLpjGUQAmtA941t7mNSGmu66jf4s',
    appId: '1:1098537331781:web:5b0af49bbcf4d2219ac72c',
    messagingSenderId: '1098537331781',
    projectId: 'carrental-a63a7',
    authDomain: 'carrental-a63a7.firebaseapp.com',
    storageBucket: 'carrental-a63a7.firebasestorage.app',
    measurementId: 'G-21Y0JL8ETP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsBBVOqZunH0DAO1uC1gK8Se9svj44xmA',
    appId: '1:1098537331781:android:6cc87594e4e24c049ac72c',
    messagingSenderId: '1098537331781',
    projectId: 'carrental-a63a7',
    storageBucket: 'carrental-a63a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2qZ0ZCF3SO-Ig0gnVKiqPDePXczpux-0',
    appId: '1:1098537331781:ios:fd4aed559ba9f55b9ac72c',
    messagingSenderId: '1098537331781',
    projectId: 'carrental-a63a7',
    storageBucket: 'carrental-a63a7.firebasestorage.app',
    iosBundleId: 'com.example.carrental',
  );
}
